# Set these to override the default settings from stencil_app_config.
# Otherwise leave blank to use stencil_app_config.
[app_settings]
# Where to store log files.
logging_path = ""
# Where you want the file to be saved to.
path = ""
# Show dubugging log calls.
# Replace as non-quoted lowercase bool (eg. true, not "true" or True).
debug = ""

[file_settings]
# string
file_name = ""

# string
template = ""


