[app_settings]
# Where to store log files.
logging_path = '/home/tmd/.log_files/'
# Where you want the file to be saved to.
path = '/mnt/c/Users/zkddu/OneDrive/Documents'

[file_settings]
# string
file_name = ""

# string
template = "bland_template.txt.jinja2"

# string
author = ""

# string
code_type = ""

# List[string]
row_list = [""]

# string
created_on = "2022-09-23"

