[app_settings]
# Where to store log files.
logging_path = '/home/tmd/.log_files/'
# Where you want the file to be saved to.
path = '/mnt/c/Users/zkddu/OneDrive/Documents'

[file_settings]
# string
file_name = "WrittenByCode.sql"

# string
template = "sproc_template.sql"

# string
author = "Terry Dullaghan"

# integer
error_number = 510

# string
error_blurb = "Not an error really."

# string
db_ref = "Prod"

# string
description = "Aha"

# string
commentary = ""

