[app_settings]
# Where to store log files.
logging_path = '/home/tmd/.log_files/'
# Where you want the file to be saved to.
path = 'C:/Users/zkddu/OneDrive/Documents'

[file_settings]
template = "bland_template.py"
